### ISSUE TITLE
[Anon] Bug report: Frostgrave.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/frostgrave#38]
**File:** Frostgrave.gstz

**BattleScribe version:** 2.00.24

**Platform:** Android

**Dropbox:** No

**Description:** Just having trouble adding magic items and weapons. Also if there were a way to do the base and whatnot that would be cool. The categories Inn and Additional Soldiers has nothing in it. Also not sure if you're planning on putting in the other campaigns.

**Comment by Vescarea** [comment]
Additional soldiers only appear when the correct selections are made such as rasied zombie spell or selecting kennel in the base and base resources

**Comment by Vescarea** [comment]
Please see the video on you tube frostgrave tutorial
