### ISSUE TITLE
V10 Issues

### ISSUE THREAD

**Issue by Jmulroy** [BSData/frostgrave#42]
Hello and thank you for your work on Battlescribe.  I and having a lot of issues trying to update my warband property.  I am using Frostgrave Version 10.1 with battle scribe V2.01.05   on a Mac.  
1. I cannot add magic weapons or any items
2. I can only add a brewery or a Lab nothing else
3. I am playing as a necro and the additional member slot for Zombie will not come up...

Help Please??

**Comment by Vescarea** [comment]
Apologies for the late reply, a newer revised version is in the works made to be straight forward book kepping system.
