### ISSUE TITLE
Join Request

### ISSUE THREAD

**Issue by Sixpacksix** [BSData/frostgrave#45]
So I got into Frostgrave lately and got ALL rulebooks and expansions to the game. But the roster builder doesnt have all soldiers and other equipment of all expansion books. I'd like to volunteer and work on it.

Sixpacksix

**Comment by amis92** [comment]
Hi @Sixpacksix sorry for the late response - are you still interested?

**Comment by Sixpacksix** [comment]
Yes, I am. But I'm new to programming this kind of resource. Any sugestions?

Gesendet: Sonntag, 27. September 2020 um 22:35 Uhr
Von: "Amadeusz Sadowski" <notifications@github.com>
An: "BSData/frostgrave" <frostgrave@noreply.github.com>
Cc: "Sixpacksix" <christian-gerbig@web.de>, "Mention" <mention@noreply.github.com>
Betreff: Re: [BSData/frostgrave] Join Request (#45)


 

Hi @Sixpacksix sorry for the late response - are you still interested?

**Comment by amis92** [comment]
/invite

The bot will comment in a minute - you'll have useful links and info there.

---
[Workflow run](https://github.com/BSData/chatops/actions/runs/291782175)
:robot: Invited @Sixpacksix with **push** access. Invite can be accepted on https://github.com/BSData/frostgrave/invitations
