### ISSUE TITLE
Join Request

### ISSUE THREAD

**Issue by Azarack** [BSData/frostgrave#46]
I would like to help update to 2nd edition of the game.

**Comment by amis92** [comment]
Hi @Azarack sorry for the late response - are you still interested?

**Comment by Azarack** [comment]
Yes, I was able to get a few things working and think it would be helpful for the process of updating to version 2.

**Comment by amis92** [comment]
/invite

---
[Workflow run](https://github.com/BSData/chatops/actions/runs/278159880)
:robot: Invited @Azarack with **push** access. Invite can be accepted on https://github.com/BSData/frostgrave/invitations
