### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by oggurt-da-bog-zombie** [BSData/frostgrave#49]
Would like to see if I can help finish the Frostgrave v2 update, thanks!

**Comment by Mad-Spy** [comment]
Are people still actually using BS for Frostgrave, given that this repo hasn't been updated in 6 years? Is it worth resurrecting this repo?

**Comment by oggurt-da-bog-zombie** [comment]
Well, what is the alternative, a totally new repo? Either way I'd like to take a shot at a Frostgrave v2 repo, seemed easier to look at the old repo and peel it apart to figure out how best to update to v2.

But I'm open to either I suppose, thanks!

**Comment by amis92** [comment]
Go ahead then in here. We're mostly keeping multiple editions within a single repository.

**Comment by amis92** [comment]
/invite

---
[Workflow run](https://github.com/BSData/chatops/actions/runs/3007327079)
:robot: Invited @oggurt-da-bog-zombie with **push** access. Invite can be accepted on https://github.com/BSData/frostgrave/invitations
