### ISSUE TITLE
[Anon] Bug report: Frostgrave.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/frostgrave#7]
**File:** Frostgrave.gstz

**BattleScribe version:** 1.15.07

**Platform:** Windows

**Dropbox:** No

**Description:** Thief wrong spelling (it says Theif*)

When you give a second weapon to a apprentice, it makes the roster invalid (although the rules allow you to do so)

**Comment by Vescarea** [comment]
Thanks for the report, the issue's you have raised have been resolved.
